spring.application.name=Transaction

spring.datasource.url=jdbc:postgresql://localhost:5432/Transactional
spring.datasource.username=postgres
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=9191

#Enabling transaction debug logs
logging.level.org.springframework.transaction=DEBUG
logging.level.org.hibernate.transaction=DEBUG
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG

